const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../source/assets'),out=path.resolve(__dirname,'../output/configuration');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[],checks=[];try{
const ctx=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,acceptDownloads:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.host!=='appassets.androidplatform.net')return r.abort();const f=path.resolve(root,u.pathname.replace(/^\/assets\//,''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f))return r.fulfill({status:404});return r.fulfill({path:f,contentType:({'.js':'application/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.woff2':'font/woff2'})[path.extname(f)]});});
await p.goto('https://appassets.androidplatform.net/assets/tools/tools_offline.html?mode=standalone#configuration-deploy');await p.waitForSelector('#kit-deploy-example');
assert.equal(await p.locator('#tool-configuration-deploy').isVisible(),true);assert.match(await p.locator('.kit-deploy-banner').textContent(),/not available/);assert.equal(await p.locator('#kit-deploy-run').isDisabled(),true);
await p.locator('#kit-deploy-batch').fill('Line test 01');await p.locator('#kit-deploy-operator').fill('Station 2');
for(const stack of ['betaflight','ardupilot','px4']){
 await p.locator('[data-deploy-stage="1"]').click();await p.locator('#kit-deploy-stack').selectOption(stack);await p.locator('#kit-deploy-save').click();await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent==='Template saved on this device.');
 await p.locator('[data-deploy-stage="2"]').click();await p.locator('#kit-deploy-preview').click();await p.waitForFunction(()=>!document.querySelector('#kit-deploy-run').disabled);assert.match(await p.locator('#kit-deploy-preview-results').textContent(),/kept per drone/);
 if(stack==='betaflight'){await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,'Configuration-workbench.png')});}
 await p.locator('#kit-deploy-to-run').click();await p.locator('#kit-deploy-run').click();await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent.startsWith('Practice run finished.'));const latest=await p.evaluate(()=>JSON.parse(localStorage.getItem('fieldkit-deploy-runs'))[0]);assert.equal(latest.template.stack,stack);assert.equal(latest.units.length,3);assert.ok(latest.units.every(u=>u.state==='verified'));assert.equal(latest.job.batch,'Line test 01');checks.push(stack+' three-unit batch with backup and readback');
}
assert.equal(await p.locator('#kit-deploy-saved option').count(),4);
await p.reload();await p.waitForSelector('#kit-deploy-example');assert.equal(await p.locator('#kit-deploy-saved option').count(),4);await p.locator('#kit-deploy-saved').selectOption({index:1});assert.equal(await p.locator('#kit-deploy-stack').inputValue(),'px4');
await p.locator('#kit-deploy-file').setInputFiles({name:'test.params',mimeType:'text/plain',buffer:Buffer.from('1\t1\tMPC_XY_VEL_MAX\t7\t9\n1\t1\tMAV_SYS_ID\t99\t6\n')});await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent.startsWith('File loaded.'));await p.locator('[data-deploy-stage="2"]').click();await p.locator('#kit-deploy-preview').click();await p.waitForFunction(()=>!document.querySelector('#kit-deploy-run').disabled);await p.locator('[data-deploy-stage="1"]').click();await p.locator('#kit-deploy-text').fill('1 1 MPC_XY_VEL_MAX 8 9');assert.equal(await p.locator('#kit-deploy-run').isDisabled(),true);checks.push('File import, saved template reload and edit invalidates comparison');
await p.locator('#kit-deploy-file').setInputFiles({name:'bad.param',mimeType:'text/plain',buffer:Buffer.from('FOO NaN')});await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent.includes('finite'));assert.equal(await p.locator('#kit-deploy-run').isDisabled(),true);
for(const fault of ['reject','disconnect','readback']){await p.locator('[data-deploy-stage="1"]').click();await p.locator('#kit-deploy-example').click();await p.locator('[data-deploy-stage="2"]').click();await p.locator('#kit-deploy-fault').selectOption(fault);await p.locator('[data-deploy-stage="2"]').click();await p.locator('#kit-deploy-preview').click();await p.waitForFunction(()=>!document.querySelector('#kit-deploy-run').disabled);await p.locator('#kit-deploy-to-run').click();await p.locator('#kit-deploy-run').click();await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent.startsWith('Practice run stopped.'));const latest=await p.evaluate(()=>JSON.parse(localStorage.getItem('fieldkit-deploy-runs'))[0]);assert.equal(latest.units.length,1);assert.equal(latest.units[0].state,'incomplete');checks.push(fault+' stops queue');}
await p.locator('#kit-deploy-history').evaluate(e=>e.parentElement.open=true);const download=p.waitForEvent('download');await p.locator('#kit-deploy-history button').first().click();const dl=await download;await dl.saveAs(path.join(out,'Sample-practice-report.html'));const html=fs.readFileSync(path.join(out,'Sample-practice-report.html'),'utf8');assert.match(html,/SOFTWARE SIMULATION/);assert.match(html,/backupHash/);checks.push('Exported HTML report includes full before backup and simulation label');
await p.locator('[data-deploy-stage="1"]').click();await p.locator('#kit-deploy-stack').selectOption('ardupilot');await p.locator('#kit-deploy-pull').click();await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent.startsWith('Read DEMO-1'));assert.match(await p.locator('#kit-deploy-text').inputValue(),/COMPASS_OFS_X/);checks.push('Practice pull fills editor');
for(const width of [360,393,800]){await p.setViewportSize({width,height:852});if(!(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))){console.log(await p.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,els:[...document.querySelectorAll('*')].filter(e=>e.getClientRects().length&&e.getBoundingClientRect().right>innerWidth+1).map(e=>[e.tagName,e.id,e.className,e.getBoundingClientRect().right]).slice(-25)})));await p.screenshot({path:path.join(out,'Overflow.png')});throw Error('Phone layout overflow');}const overflow=await p.locator('#tool-configuration-deploy').evaluate(e=>[...e.querySelectorAll('input:not([type=checkbox]),select,textarea,button')].filter(x=>x.getClientRects().length&&x.getBoundingClientRect().right>innerWidth).map(x=>x.id));assert.deepEqual(overflow,[]);checks.push(width+'px controls fit');}
await p.setViewportSize({width:393,height:852});await p.locator('[data-deploy-stage="1"]').click();await p.locator('#kit-deploy-example').click();await p.locator('[data-deploy-stage="2"]').click();await p.locator('#kit-deploy-fault').selectOption('none');await p.locator('[data-deploy-stage="2"]').click();await p.locator('#kit-deploy-preview').click();await p.waitForFunction(()=>!document.querySelector('#kit-deploy-run').disabled);await p.locator('#kit-deploy-to-run').click();await p.locator('#kit-deploy-run').click();await p.waitForFunction(()=>document.querySelector('#kit-deploy-status').textContent.startsWith('Practice run finished.'));await p.locator('#kit-deploy-run-results').screenshot({path:path.join(out,'Batch-results.png')});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'UI-validation.json'),JSON.stringify({checks,errors,physicalDeviceConfigured:false},null,2));console.log(checks);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
