'use strict';
const assert=require('node:assert/strict'),{test}=require('node:test');
const D=require('../source/assets/tools/fieldkit-deployment.js');
const template=stack=>{const s=D.demo(stack)[0];return D.makeTemplate({name:'Line standard',stack,board:s.board,firmware:s.firmware,text:D.example[stack]});};
const setup=(stack='ardupilot',fault='none')=>{const adapter=new D.PracticeAdapter(stack,fault),saved=[],ledger={save:async r=>saved.push(D.clone(r))};return {adapter,saved,ledger,template:template(stack),targets:adapter.drones.map(d=>d.uid),job:{batch:'WO-101',operator:'Station 2'}};};
for(const stack of ['betaflight','ardupilot','px4']){
 test(stack+': three units backed up, applied, saved and read back',async()=>{const o=setup(stack),before=D.clone(o.adapter.drones);const write=o.adapter.write.bind(o.adapter);o.adapter.write=async(uid,c)=>{const r=o.saved.at(-1),u=r.units.find(u=>u.uid===uid);assert.equal(u.backup.uid,uid);assert.equal(u.backupHash.length,64);assert.ok(u.attempted.includes(c.key));return write(uid,c);};const r=await D.run(o);assert.equal(r.state,'finished');assert.equal(r.evidence,'simulation');assert.equal(r.job.batch,'WO-101');assert.equal(r.units.length,3);for(const [i,u]of r.units.entries()){assert.equal(u.state,'verified');assert.equal(u.attempted.length,u.verified.length);assert.equal(u.backup.uid,before[i].uid);for(const k of Object.keys(before[i].entries).filter(k=>D.keepPerDrone(stack,k)))assert.deepEqual(o.adapter.drones[i].entries[k],before[i].entries[k]);}const writes=o.adapter.writes.length;const again=await D.run(o);assert.ok(again.units.every(u=>u.state==='no-changes'));assert.equal(o.adapter.writes.length,writes);});
 test(stack+': mismatched board and firmware prevent writes',async()=>{for(const key of ['board','firmware','stack']){const o=setup(stack);o.template[key]='wrong';const r=await D.run(o);assert.equal(r.units[0].state,'blocked');assert.equal(o.adapter.writes.length,0);assert.equal(r.units.length,1);}});
 test(stack+': backup roundtrip preserves supported values and types',()=>{const s=D.demo(stack)[0],p=D.parse(stack,D.exportText(s));for(const [key,v]of Object.entries(s.entries)){assert.equal(p.entries[key].value,v.value);if(stack!=='betaflight')assert.equal(p.entries[key].type,v.type);}});
}
test('Betaflight PID and rate profiles remain separate',()=>{const text='# Betaflight / STM32F405 (S405) 4.5.2\nboard_name X\nset vtx_channel = 1\nprofile 0\nset p_roll = 40\nprofile 1\nset p_roll = 45\nrateprofile 0\nset roll_rc_rate = 100\nsave\n';const p=D.parse('betaflight',text);assert.equal(p.entries['profile/1/set p_roll'].value,'45');assert.equal(p.entries['rateprofile/0/set roll_rc_rate'].value,'100');assert.deepEqual(D.parse('betaflight',D.exportText({...p})).entries,p.entries);});
test('Betaflight reset/save omitted; unsupported commands rejected',()=>{const p=D.parse('betaflight','defaults nosave\nset vtx_channel = 2\nsave\n');assert.equal(p.warnings.length,1);assert.equal(Object.keys(p.entries).length,1);assert.throws(()=>D.parse('betaflight','flash_erase'),/Unsupported/);});
test('Duplicate values and mixed component files rejected',()=>{assert.throws(()=>D.parse('ardupilot','FOO 1\nFOO 2'),/Duplicate/);assert.throws(()=>D.parse('betaflight','set foo = 1\nset foo = 2'),/Duplicate/);assert.throws(()=>D.parse('px4','1 1 FOO 1 9\n1 2 BAR 2 9'),/Mixed/);});
test('Numeric bounds, names and unsupported 64-bit types fail',()=>{for(const text of ['FOO NaN','FOO Infinity','FOO 0x10','NAME_TOO_LONG_HERE 1','1 1 FOO 256 1','1 1 FOO -1 5','1 1 FOO 1 7'])assert.throws(()=>D.parse('px4',text));assert.equal(D.parse('ardupilot','FOO,-0.1').entries.FOO.value,-.1);});
test('MAVLink bytewise integers retain all bits, C-cast rejects precision loss',()=>{assert.deepEqual([...D.paramValueBytes(16777217,6,'bytewise')],[1,0,0,1]);assert.deepEqual([...D.paramValueBytes(-2,4,'bytewise')],[254,255,0,0]);assert.throws(()=>D.paramValueBytes(16777217,6,'c-cast'),/precision/);assert.equal(new DataView(D.paramValueBytes(.14,9,'bytewise').buffer).getFloat32(0,true),Math.fround(.14));});
test('Typeless export does not invent MAVLink types',()=>{const s={stack:'ardupilot',board:'X',firmware:'1',entries:{FOO:{value:1},BAR:{value:.2}}};const p=D.parse('ardupilot',D.exportText(s));assert.equal(p.entries.FOO.type,null);});
test('Profile export places master settings before profiles',()=>{const s={stack:'betaflight',board:'X',firmware:'4.5.2',entries:{'profile/0/set p_roll':{value:'40'},'set vtx_channel':{value:'2'}}};const text=D.exportText(s);assert.ok(text.indexOf('vtx_channel')<text.indexOf('profile 0'));assert.equal(D.parse('betaflight',text).entries['set vtx_channel'].value,'2');});
for(const [name,mutate]of [['unknown setting',o=>o.template.entries.DOES_NOT_EXIST={value:1}],['unknown type',o=>o.adapter.drones[0].entries.WPNAV_SPEED.type=null],['read-only',o=>o.adapter.drones[0].entries.WPNAV_SPEED.writable=false],['range',o=>o.template.entries.WPNAV_SPEED.value=3000],['incomplete catalog',o=>o.adapter.drones[0].complete=false],['armed',o=>o.adapter.drones[0].armed=true],['armed state unknown',o=>delete o.adapter.drones[0].armed],['broadcast target',o=>o.adapter.drones[0].componentId=0],['unknown encoding',o=>o.adapter.drones[0].encoding='guess']])test(name+' prevents all writes',async()=>{const o=setup();mutate(o);const r=await D.run(o);assert.equal(r.units[0].state,'blocked');assert.equal(o.adapter.writes.length,0);});
for(const fault of ['reject','disconnect','readback'])test(fault+' stops batch and never passes affected drone',async()=>{const o=setup('px4',fault),r=await D.run(o);assert.equal(r.state,'stopped');assert.equal(r.units[0].state,'incomplete');assert.equal(r.units.length,1);assert.ok(o.adapter.writes.every(w=>w.uid===o.targets[0]));assert.ok(r.units[0].errors.length);});
test('Quota/storage failure prevents write',async()=>{const o=setup();o.ledger.save=async()=>{throw Error('Quota exceeded');};await assert.rejects(D.run(o),/Quota/);assert.equal(o.adapter.writes.length,0);});
test('Configuration changed after comparison prevents write',async()=>{const o=setup();o.expected=Object.fromEntries(o.adapter.drones.map(s=>[s.uid,D.fingerprint(s)]));o.adapter.drones[0].entries.WPNAV_SPEED.value=401;const r=await D.run(o);assert.equal(r.units[0].state,'blocked');assert.equal(o.adapter.writes.length,0);});
test('Second read identity/state drift prevents write',async()=>{const o=setup(),read=o.adapter.read.bind(o.adapter);o.adapter.read=async uid=>{const s=await read(uid);if(o.adapter.reads===2)s.armed=true;return s;};const r=await D.run(o);assert.equal(r.units[0].state,'blocked');assert.equal(o.adapter.writes.length,0);});
test('Unchanged calibration corrupted on commit fails readback',async()=>{const o=setup(),commit=o.adapter.commit.bind(o.adapter);o.adapter.commit=async uid=>{const r=await commit(uid);o.adapter.drones[0].entries.COMPASS_OFS_X.value=999;return r;};const r=await D.run(o);assert.equal(r.units[0].state,'incomplete');assert.match(r.units[0].errors[0],/Untouched setting/);});
test('Failure on second unit keeps first passed and third untouched',async()=>{const o=setup(),write=o.adapter.write.bind(o.adapter);o.adapter.write=async(uid,c)=>{if(uid===o.targets[1])throw Error('Disconnected');return write(uid,c);};const r=await D.run(o);assert.equal(r.units[0].state,'verified');assert.equal(r.units[1].state,'incomplete');assert.equal(r.units.length,2);assert.equal(o.adapter.drones[2].entries.WPNAV_SPEED.value,400);});
test('Cancellation before first read prevents write',async()=>{const o=setup(),c=new AbortController();c.abort();o.signal=c.signal;const r=await D.run(o);assert.equal(r.state,'stopped');assert.equal(o.adapter.writes.length,0);});
test('Live gate cannot silently use practice',async()=>{assert.equal(D.LIVE_CONFIG_WRITE_GATE,false);assert.throws(()=>new D.NativeAdapter(),/LIVE_CONFIG_WRITE_GATE/);const o=setup();o.adapter.mode='usb';await assert.rejects(D.run(o),/LIVE_CONFIG_WRITE_GATE/);assert.equal(o.adapter.writes.length,0);});
